.github/CODEOWNERS, README.md, kepler/tools/merge-upstream-pull-request.sh, modular_kepler/README.md
To kepler-ify the codebase, well, start to. Also to test the webhook system. 
Branching away
tweak: Removes a few citadel-related wording spaces
/:cl:
=> Initial kepler-ifying

kepler/tools/merge-upstream-pull-request.sh
This changes the script that makes the mirror work
Its important to the project working
:cl:
server: Updated merge script
/:cl:
=> Tweaks to the script

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/PubbyStation/PubbyStation.dmm
This PR removes the following from all maps:
- Aphrodisiac
- The kink vendor
- The rooms hidden in maintenance
Mapdiffbot will handle changed images
Needed for server conversion
:cl:
del: Removed lewd stuff from maps
/:cl:
=> Removes lewdness from the maps

TGS3.json
This adds BSQL.dll and RustG.dll to the TGS3 config file. These are kinda important to making the server work.
Things need to work
=> Adds BSQL and Rust-G to TGS3

TGS3.json
Removes all DLLs from our TGS3 file, because this fixed the problem for me
A working database is kinda important
server: Modified TGS3.json
/:cl:
=> The real TGS3 Fix

code/modules/food_and_drinks/recipes/drinks_recipes.dm
Readds both Strawberry milk and tea so its no longer a uncraftable drink
Replaced the lewd chems with simple cherryjelly as its also pink
As funny as it is to be only able to get it from random seeds or a SCP vender. They should be added in
:cl:
add: removed content
/:cl:
=> Re-adds Strawberry milk/tea

code/datums/dna.dm, code/game/objects/items/devices/scanners.dm, code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, code/modules/mob/dead/new_player/preferences_setup.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/human/human_defines.dm, modular_citadel/code/modules/mob/living/carbon/human/species_types/jellypeople.dm
This fixes `Random Body` to stop it from giving people things they shouldnt have
Slimes shouldnt have snouts
:cl:
fix: You can no longer get snouts on a slime, as well as other species things that shouldnt happen
/:cl:
=> Fixes species stuff

code/controllers/subsystem/chat_prompts.dm, config/idle_announce.txt, tgstation.dme
This should add a little text linking people from in-game to the discord, website, and rules page.
It fires every 10 minutes or so, in normal-size text.
Right now it only uses one line, however more can be added by following the example in the `idle_announce` file.
Brings more notice to the discord and rules.
add: SSChat_prompt - a small message will pop up in the chat window every 10 minutes, with helpful information
/:cl:
=> SSChat_prompt

code/controllers/subsystem/vote.dm
This reverts commit bf77ffe3efe39246b23fa39a60dee5b31322346c.
Long story short, #71 got merged, but didnt count as merged on the GitHub, so it all went tits up
=> Revert "Removes roundstart game vote"

code/controllers/subsystem/vote.dm
This should remove the roundstart vote, without affecting anything else. (bash me if it does)
Without it, the game defaults to Secret.
The roundstart vote isn't needed, at all.
:cl:Alonefromhell
del: Removed roundstart vote
/:cl:
=> Removes roundstart game vote

code/controllers/configuration/entries/game_options.dm, code/controllers/subsystem/ticker.dm, config/game_options.txt
Kills off roundstart voting. Should. Finally.
Please, no more.
tweak: Roundstart voting is now a config option
config: Disabled roundstart voting
/:cl:
=> roundstart vote as config

code/controllers/subsystem/input.dm
Rebinds some shortcuts.
Easier access to verbs.
tweak: input tweaks - LOOC is now "L", Whisper is now "U", Subtle is now "N"
/:cl:
=> Input Shortcuts

code/game/objects/items/cards_ids.dm, modular_citadel/code/game/objects/ids.dm, modular_kepler/code/game/objects/ids.dm, modular_kepler/code/game/objects/items/cards_ids.dm, tgstation.dme
You can now use the emag for a total of INFINITY times.
Keeping the value itself for any future badminnery
Fixes: #171 
requested by @AffectedArc07 
tweak: Emag can now be used an INFINITY amount of times. Have fun.
/:cl:
=> To infinity and beyond

modular_kepler/code/modules/client/preferences.dm, tgstation.dme
This should re-enable flavor text.
Tested as working.
Fixes: #182 
People like their snowlake text.
fix: Flavor text works properly, again.
/:cl:
=> Flavor text fix

modular_citadel/code/modules/mentor/mentor_memo.dm, modular_kepler/code/modules/mob/dead/new_player/tos_procs.dm
Basically finished off what I didnt do properly in #113 
Better performance with datums that dont hang, and it stops admins getting spammed
:cl:
fix: Actually fixed undeleted SQL Queries
/:cl:
=> Fixes undeleted SQL queries (Again)

code/game/objects/items/devices/PDA/PDA.dm
This PR fixes some issues with the PDA redesign I did before, mainly categories and misaligned items.
Fixes: #192
Fixes: #169
Stuff should be done properly or not at all
fix: PDA UI is now properly spaced out
/:cl:
=> Fixes some oversights in the PDA redesign

code/controllers/configuration/entries/general.dm, config/config.txt, interface/interface.dm, modular_kepler/interface/skin.dmf, tgstation.dme
This changes the forum button in the top right of the UI to a discord button. Also changes the relevant config option
A link to the discord ingame is a better resource than a forum link, imo, as people can get contact about issues *much* faster on the discord as opposed to the forums. That and most people already have discord accounts as opposed to forum accounts
:cl:
tweak: The UI Forum button is now a Discord button
/:cl:
=> Changes forum button to discord button

modular_citadel/code/modules/client/loadout/head.dm
Adds the kitty ears as a loadout option because people wanted it.
It's not.
:cl:
add: Kitty ears as a loadout option
/:cl:
=> Adds kitty ears as a loadout option

code/modules/jobs/map_changes/map_changes.dm
Includes Omegastation's job change file.
Fixes: #257
:cl:
fix: [Omegastation] Jobs that shouldn't be available, should no longer appear
/:cl:
=> Omega job fix

code/modules/goonchat/browserassets/css/browserOutput.css
Merges a missing merge.
Fixes:  #328
:cl:
fix: Chat colors for dark mode should work now, and look good.
/:cl:
=> Chat color

_maps/map_files/OmegaStation/OmegaStation.dmm
Moved a trash bin, removed a double door, fixed an ID issue with a shutter in AI satellite.
Fixes: #243, #242 
:cl:
tweak: [Omega] Trash bin in robotics has moved slightly.
fix: [Omega] Double door between robotics and toxins has been fixed.
fix: [Omega] Window shutters in AI Sat should work now.
/:cl:
=> [Omega] Map fixes

_maps/map_files/Deltastation/DeltaStation2.dmm
Fixes me forgetting to type `git push`
We dont want this room here
=> Fixes a map edit that shouldnt have happened

modular_citadel/code/modules/client/verbs/who.dm
Fixes #381
This PR merges `Mentorwho` and `Adminwho` together into just `Adminwho`, and tweaks the behaviour of `Who` to show everyone in one block, but color the names of admins and mentors.
Merge things to how they are on other servers, and means we have one less verb to deal with
tweak: Mentorwho and adminwho have been merged into adminwho
tweak: Admins and mentors now highlight in who instead of being in a seperate categorey
/:cl:
=> Tweaks to Adminwho and Who

code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
One of the upstream merges broke dreamchecker, this PR is a hotfix for that
Slightly de-shittified code is good
:cl: AffecredArc07
code: Made a very minor code tweak
/:cl:
=> Dreamchecker fail hotfix

code/modules/research/techweb/all_nodes.dm
Does what it says. One piece of tech was missing from the web, the other misplaced, after mirror merge from upstream, this fixes that.
Fixes: #481
:cl:
fix: Advanced Slime upgrade disk is now available again
/:cl:
=> Fixes some mistakes in the techweb

html/templates/header.html
Updates the changelog template, so it links and displays our stuff.
Fixes: #434
:cl:
tweak: Keplerfies the changelog display
/:cl:
=> Updates changelog to our codebase

code/modules/mob/living/silicon/ai/say.dm, modular_citadel/code/modules/mob/mob.dm
Fixes AIs not being able to talk through holopads.
Fixes: #480
Being able to talk through the holopads is good for the AI.
:cl:
fix: AIs can now use Holopads again.
/:cl:
=> Fixes holopads for AIs

code/_onclick/adjacent.dm
Fixes #521
I forgot to check this when I made us dreamchecker compatible. Oops.
You should be able to use windoors from the outside
fix: You can use windows and windoors from the outside again
/:cl:
=> Fixes windoors

code/__DEFINES/kepler_defines.dm, code/modules/client/verbs/ooc.dm, tgstation.dme
Mentors now have their own OOC color. Respects BYOND member status/color, although only for the name part of the message.
Let the slaves have their tiny gifts.
:cl:
add: Mentor OOC color.
/:cl:
=> Mentor OOC color.

code/modules/mob/say_vr.dm
Removes the `Subtler` emote.
ERP is bad.
:cl:
del: Removed the Subtler emote. Use the normal Subtle instead.
/:cl:
=> Removes Subtler

code/_onclick/hud/human.dm
Does what it says in the title.
Imagine calling a pocket for `storage1`. pff.
:cl:
spellcheck: Pockets have been renamed. They actually make IC sense now.
/:cl:
=> Renames pockets

code/modules/admin/admin.dm
Are you *really* sure you want to start the round?
Premature round start does no-one any good.
:cl:
add: Start Round admin verb now has a confirmation box
/:cl:
=> Start round confirmation

modular_citadel/code/modules/mentor/mentorhelp.dm, modular_citadel/code/modules/mentor/mentorpm.dm
Changes the
It helps distinguish between an adminhelp and a mentorhelp
:cl:
tweak: Changed the mentorhelp sound from bikehorn.ogg to twobeep.ogg
/:cl:
=> Mentohelp Noise change

code/modules/mob/dead/new_player/new_player.dm
Since we're not gonna be using omega, this thing can go away.
:cl:
code: Reverted a hotfix (PR #797)
/:cl:
=> Revert omega job snowflake

modular_citadel/code/modules/mob/mob.dm
Makes custom emotes check for content.
Silly blank emotes are silly.
:cl:
fix: Custom emotes can no longer be blank.
/:cl:
=> Check for input in custom emotes

code/modules/surgery/organs/organ_internal.dm, code/modules/surgery/organs/tongue.dm
Fixes a runtime caused by incorrect tongue type.
Constant runtimes bad.
:cl:
fix: Plasmaman tongue is now the correct type, and no longer causes constant runtimes.
/:cl:
=> Plasmaman tongue runtime fix

code/modules/clothing/spacesuits/hardsuit.dm
Fixes #957 
Hardsuits should be hardsuits
:cl:
fix: Fixed hardsuit helmets not being spaceproof.
/:cl:
=> Hardsuit helmets are spaceproof again

_maps/map_files/BoxStation/BoxStation.dmm, code/game/machinery/turnstile.dm
Maps in genpop on Boxstation.
Genpop nice. Genpop smooth.
:cl:
add: Genpop has been mapped into security
/:cl:
=> Genpop on Box!

code/game/machinery/turnstile.dm
Fixes #985
Turnstiles now respect timings when youre inside them
Chat spam is bad
fix: Turnstiles no longer spam your chat if you go through them the wrong way
/:cl:
=> Fixes turnstile timing issues

code/datums/emotes.dm, modular_citadel/code/modules/mob/cit_emotes.dm
Title. Hopefully without breaking anything.
Fixes: #987
Emote spam be bad
:cl:
fix: Emotes can no longer be spammed
/:cl:
=> Fixes emote spam

code/controllers/subsystem/shuttle.dm
Title.
Too many points is no-no.
:cl:
fix: Supply point generation have been reduced to a somewhat sane level
/:cl:
=> Significantly reduce supply point generation

code/modules/clothing/masks/miscellaneous.dm, code/modules/vending/autodrobe.dm
This PR removes the joy mask
Why did this thing even exist
del: Removed joy mask
/:cl:
=> Removes joy mask

code/__DEFINES/nanites.dm, code/modules/research/nanites/nanite_programs/sensor.dm, code/modules/research/nanites/nanite_programs/suppression.dm, code/modules/research/nanites/nanite_programs/utility.dm, code/modules/research/nanites/nanite_programs/weapon.dm
Ports https://github.com/tgstation/tgstation/pull/47437
```
Fails on compile time if there's an error, instead of silently not working.
```
:cl:
code: Nanite defines
/:cl:
=> Nanite defines

.github/CODEOWNERS
Does what it says in the title.
I dont want files that change the configs to slip in without said configs being changed
None because this doesnt actually impact the game.
=> Adds myself as a code owner for config files

code/__DEFINES/nanites.dm, code/controllers/subsystem/processing/nanites.dm, code/modules/research/designs/nanite_designs.dm, code/modules/research/nanites/nanite_programs/utility.dm, code/modules/research/techweb/all_nodes.dm
Ports https://github.com/tgstation/tgstation/pull/47098 with minor changes.
- Gives science an incentive to spread nanites as much as possible.
- Gives non-science a small incentive to get nanites (more points = more chance of getting that research you need).
- Softens the blow when someone rushes nanites, since they can potentially get those points back over time.
:cl: XDTM
add: Added the Distributed Computing nanite program, which slowly adds research points over time.
add: Added the Neural Network nanite program, which adds research points over time as well, but scales in efficiency for each mob that is currently running the program, breaking even with Distributed Computing at 3 hosts.
add: All of these programs only work on complex mobs (humans, monkeys, xenomorphs) and only have 25% …
=> Adds research-boosting programs for nanites

code/game/machinery/washing_machine.dm, code/modules/clothing/gloves/_gloves.dm, code/modules/clothing/shoes/_shoes.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/reagents/chemistry/reagents/other_reagents.dm
Fixes some `clean_blood()` crap, my worst enemy right now
Code should work
This **MIGHT** fix the open issue with blood at the moment, but not sure
:cl:
tweak: Very minor tweaks to blood cleaning
/:cl:
=> More Dreamchecker Crap

code/modules/mob/living/carbon/human/human.dm, code/modules/reagents/chemistry/reagents/medicine_reagents.dm, code/modules/surgery/bodyparts/dismemberment.dm
Fixes #1138 
This PR will make it so using admin heal will force heal every bone in the body
Admin healing someone should fix their damn bones
:cl:
fix: Admin revives now heal broken bones
/:cl:
=> Fixes bones not being unbroken on admin rejuv

code/game/machinery/cryopod.dm
As the title describes.
Fixes #1083
:cl:
fix: Silicons(borgs and AI) can interact with cryopod console again.
/:cl:
=> Fixes silicon interaction with cryopod console

code/_globalvars/lists/mobs.dm, code/game/atoms.dm, code/game/objects/effects/decals/cleanable/gibs.dm, code/game/objects/items/devices/scanners.dm, code/modules/mob/living/blood.dm, code/modules/mob/living/carbon/human/species_types/jellypeople.dm, code/modules/mob/mob_helpers.dm, code/modules/reagents/chemistry/reagents/other_reagents.dm, code/modules/reagents/chemistry/recipes/medicine.dm, code/modules/reagents/reagent_containers/blood_pack.dm
Fixes #984
Fixes #980
Slimes should have blood, for xenobio and for accurate medical
fix: Slimes have blood again
/:cl:
=> Gives slimes blood

code/modules/food_and_drinks/food/snacks_frozen.dm, code/modules/food_and_drinks/food/snacks_pastry.dm
Fixes bad reagent IDs which caused a unit test to fail on randomisation.
The game should work properly
fix: Fixed some bad reagent typepaths
/:cl:
=> Hotfix for reagents unit test
