- code/modules/mob/living/simple_animal/friendly/mouse.dm
This stops mice randomly eating wires
In lowpop, this can become a pain, and considering people dont really know the station wiremap, this is more of a hindrance than a "stop engineering getting bored" feature.
:cl:
tweak: Mice no longer eat wires
/:cl:
> Removes mice wire eating

- tools/mapmerge2/mapmerge.bat
When I added DMAPI, I staged all because it was 50 file changes. I didnt realise I staged `tools/mapmerge2/mapmerge.bat`, which I had modified because of my python path, and probably made it invalid for anyone else using it
Being able to merge maps properly is kind of important
fix: Mapmerge works on 99% of systems again
/:cl:
> Fixes mapmerge python path

- modular_citadel/code/modules/mentor/mentor.dm
- modular_citadel/code/modules/mentor/mentor_memo.dm
This PR fixes the issue of SQL queries going undeleted. It also stops these logs appearing
```
[2019-06-25 19:09:40.299] SQL: Undeleted query: "SELECT ckey FROM mentor" LA: NextRow LAT: 0.5
[2019-06-25 19:09:40.300] SQL: Undeleted query: "SELECT ckey, memotext, timestamp, last_editor FROM mentor_memo" LA: NextRow LAT: 115.5
[2019-06-25 19:09:40.301] SQL: Undeleted query: "SELECT ckey, memotext, timestamp, last_editor FROM mentor_memo" LA: NextRow LAT: 181
```
It fixes issues and stops us being spammed
:cl:
tweak: SQL queries properly delete now
/:cl:
> Fix undeleted queries

- code/game/machinery/doors/brigdoors.dm
- code/game/machinery/status_display.dm
This PR changes our status displays to use a more readable font, that has been present on all versions of windows since Vista.
Status displays are supposed to be readable, and they really arent at the moment
:cl:
tweak: Status displays have been updated. Mmmmm crispy....
/:cl:
> Crispy Status Displays

- code/modules/mob/say.dm
This changes the box for the verb `me` back to a single line textbox instead of a multiline
I would rather pressing enter to send a message instead of having to tab across to the send button. We dont need multi-line emotes here
:cl:
tweak: The "me" verb is now a single line textbox again
/:cl:
> Makes "me" a small box

- code/modules/events/aurora_caelus.dm
- code/modules/events/false_alarm.dm
This PR removes the aurora caelus random event, as well as the false alarm events, with different reasons for each
Reason for removing aurora caelus: It absolutely destroys the server and is terribly coded (It does the same on other servers, tripling the ping for most users)
Reason for removing false alarms: They cause too much distress in the round for no reason at all. You get a false alarm for a blob and everyone instantly stops what they are doing, just to realise it was all for nothing
Lag bad, fake alerts bad
del: Removed aurora caelus and false alarm random events
/:cl:
> Removes bad random events

- code/controllers/configuration/configuration.dm
- code/modules/goonchat/browserOutput.dm
- code/modules/goonchat/browserassets/js/browserOutput.js
- code/modules/mob/living/say.dm
- config/in_character_filter.txt
This PR ports TGs IC-word filtering, which allows us to easily keep netspeak out of IC chat, as well as other words (slurs for example). This is configurable server side of being hardcoded (Note to self: PR is a config change). 
If a player attempts to speak a message with a blacklisted word in it, they will be notified that they should read the rules, and the word that matched the blacklist will be highlighted.
Makes administration simpler and also discourages this kind of behaviour
add: You can now blacklist words from IC chat via config
/:cl:
> IC Word filtering

- code/game/objects/items/devices/radio/headset.dm
This PR removes the "High Volume" setting from command headsets. This setting allowed command memebers to speak with text the size of a megaphone. With no cooldown. Its a spammy mess and nobody enjoys it.
Readable radio is a nice thing to have
:cl:
del: Command members can no longer make their headset font size the same as a megaphone
/:cl:
> Removes headset loud mode

- code/modules/mob/dead/new_player/new_player.dm
This PR increases the vertical size of the new player box
The reasoning for this is after adding the TOS button, you had to scroll to fit all the UI elements in, which looked **very** bad.
You should be able to not have to scroll in a box that takes up like 1/16th of your screen
fix: The lobby options box now comfortably fits the buttons without having to scroll
/:cl:
> Makes new player panel bigger

- code/modules/goonchat/browserassets/css/browserOutput.css
- interface/stylesheet.dm
This PR changes our radio colors to be inline with paras. Examples are below
It matches department colors better (Colors on the headsets, doors, etc). Also why the hell is command an awful yellow-green color on TG code anyways?
:cl:
tweak: Department radio colors are now the same as Paradise
/:cl:
> Changes radio colors to paras

- code/__HELPERS/_logging.dm
- code/game/world.dm
- config/config.txt
- modular_kepler/code/controllers/configuration/entries/general.dm
- tgstation.dme
This PR adds in the necassary hooks for calling log-parsing at the end of each round. The issue with our current parser system is it fires off every hour, which has some issues, including but not limited to:
- Logs can take up to a full hour to appear on the site
- Logs from the current round may be published, allowing for metagaming
- Logs can be published half complete due to ongoing rounds, which wont get updated
This PR will call the logparser with configurable dirs at end round, after everyone has been moved off the server, and after logging has been shut down, to ensure were on the absolute final log files
In terms of why I am calling it so late, this is why:
- I want it called after logs have closed, to make sure we are on definite latest
- The `shell()` function is blocking, …
> End-Round Log Parsing

- code/__HELPERS/priority_announce.dm
- code/game/gamemodes/game_mode.dm
- code/game/machinery/computer/communications.dm
Changes Central Command out in favour of something less militant/blase on announcements/consoles. This is the first of many PRs to remove Nanotrasen references.
This is part of an ongoing process to make the station not be a Nanotrasen station. Central Command has been changed to Head Office and quantum entanglement now directly messages the "Board of Directors" rather than Head Office (there's effectively a two-tier system now. Faxes for regular things and quantum entanglement (which bypasses Head Office) for super emergencies).
This also changes a few references to the Syndicate. While the Syndicate will be retained, there's plans down the road for greater nuance than it simply being a nebulous shadow organization (IE: direct employment by a hostile company through the syndicate).
:cl: …
> Changes announcements/consoles.

- code/modules/client/client_procs.dm
This PR Increases our upload limit from 1MB to 10MB, because 1MB is far too small to do anything with, without brutally compressing the audio (Apologies to the ears of @CornMyCob and JT)
Bigger file uploads are better, and people want to hear audio that isnt at 8khz
tweak: Admins can now upload MIDIs and sound files larger than 1MB (Cap is 10MB)
/:cl:
> Increases Upload Limit

- code/game/objects/items/devices/PDA/PDA.dm
- code/game/objects/items/devices/PDA/cart.dm
This PR fixes the weird issues some PDA carts had, when they had functions but didn't have any menus, it would show a `Cartridge Functions` header but have no options. Also cleans up the menu and spaces things a little better
Fixes #258 
Makes menus look better and not crappy
fix: PDA will now only show cartridge functions if your cartridge has functions
/:cl:
> Fixes PDA cart menus

- code/datums/emotes.dm
- code/modules/mob/emote.dm
Fixes #194
Slimes can now squish, and everyone can no longer use the IPC emotes
Slimes need to squish, and humans shouldnt be able to beep
fix: Slimes can squish now
fix: Humans can no longer use IPC emotes
/:cl:
> Fixes emotes

- code/modules/shuttle/emergency.dm
This PR changes the green and blue alert shuttles from 20 and 12 minutes both to 10 minutes.
20 minutes is a long time.
:cl:
tweak: Green and blue alert shuttles now take just 10 minutes to arrive.
/:cl:
> shuttle changes

- code/controllers/subsystem/server_maint.dm
- code/game/world.dm
This PR moves the end round log parsing call to the `Shutdown()` of `SSserver_maint`. This should hopefully give the parser enough time to carry out its tasks instead of the line before the server is killed, as currently the server can parse `attack.log` and then it kills. This should hopefully give us enough time.
This stuff should actually work, for fucks sake affected do your job
fix: Fixes the log parser. Again.
/:cl:
> [Take 50] Makes parsing work

- modular_kepler/code/modules/mob/dead/new_player/tos_procs.dm
Fixes a runtime relating to the TOS procs, specifically when not running an SQL backend
Fixes #333
Runtimes are bad
fix: TOS procs no longer runtime when youre not using an SQL backend
/:cl:
> Fixes TOS runtime

- code/modules/mob/emote.dm
Fixes #384
Allows all xenobio slimes to squish
Having some slimes able to squish and others not is bad
fix: All slimes can squish now
/:cl:
> Fixes emotes for the billionth time

- code/game/atoms.dm
- modular_citadel/code/_onclick/click.dm
Fixes #382
Moving your mouse pointer around now makes your character look in that direction. This broke when making us dreamchecker compatible, and required some proc overriding to make it work
Intended features should work
fix: When in combat mode, your character faces your mouse cursor again
/:cl:
> Makes combat mode mouse looking work again

- code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Fixes #237
Megafauna now gib you when youre dead. The proc for this is named `devour()`, so I associated it with the V-word. `Devour` is the word that TG uses, so its staying for the sake of modularity
Megafauna now perform as intended, and logs dont get spammed
fix: Megafauna gib again
/:cl:
> Makes megafauna gib

- modular_kepler/code/modules/mob/dead/new_player/tos_procs.dm
Fixes #422
When fixing the TOS runtime, I only made sure that joining the lobby didnt runtime like I did before, instead of trying to actually join the game.
99% of the people running this code (Not running a DB backend 24/7) should be able to test, hassle free
fix: Fixed a bug in TOS code
/:cl:
> Fixes TOS again

- code/datums/dna.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/jobs/job_types/captain.dm
- code/modules/jobs/job_types/job.dm
- code/modules/mob/living/carbon/human/human_defines.dm
- code/modules/mob/living/carbon/human/human_helpers.dm
Removed the ability to be "nameless" and the ability to choose "non-binary" and "object" genders in character creation.
Recommending a testmerge to ensure i didn't horribly break something, although it should work fine.
Fixes: #435
:cl:
del: Removed the ability to be nameless
fix: "non-binary" and "object" genders are no longer selectable.
/:cl:
> Genders and nameless

- code/game/objects/items/storage/wallets.dm
Wallets now show up with an ID in them
Fixes #508 
Wallets should render properly
fix: Wallets now show up if you put an ID in them
/:cl:
> Fixes wallets

- code/datums/weather/weather_types/radiation_storm.dm
- code/modules/events/_event.dm
- code/modules/events/radiation_storm.dm
Fixes #550 
This PR tweaks radiation storms, making them more suited for out population levels.
_When the storm starts, maintenance airlocks are opened so anyone trapped can get into safety_
_When the event ends, people are given 30 seconds to leave maintenance before it goes back to how it was_
In this population size, and with nobody sat in the bridge, maintenance isnt opened for radiation storms, which has lead to people dying.
tweak: Radiation storms now give maintenance emergency access
/:cl:
> Tweaks Radiation Storms

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/Deltastation/DeltaStation2.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/OmegaStation/OmegaStation.dmm
- _maps/map_files/PubbyStation/PubbyStation.dmm
This PR modifies all on map autodrobes to the varient which require no access. This means that the mime/clown autodrobes can be accessed by anyone, but that still requires a breakin.
Fixes #549
People should be able to use things
tweak: Autodrobes can now be used by anyone, instead of just clown/mime
/:cl:
> Makes all autodrobes all access

- code/controllers/subsystem/ticker.dm
- code/game/gamemodes/game_mode.dm
Fixes #467 
This PR makes it so you can no longer be drafted into antag roles with your preference off, and so it actually shows what mode it is.
We should be respecting preferences. What is the point of an antag preference if it means nothing.
tweak: You can no longer be drafted into antagonist roles with the preference off
tweak: It now displays what the roundtype is (Usually secret)
/:cl:
> Antag Picking Tweaks

- modular_citadel/code/modules/client/verbs/who.dm
Makes the `who` verb compatible with darkmode. You should now be able to see the names of mentors without ruining your eyes.
Being able to see text easily is good.
:cl:
tweak: The color of mentors have been changed lightly in the "who" verb.
/:cl:
> Who verb mentor color

- code/game/machinery/teleporter.dm
Quick and dirty way to make sure fly persons only occur as rare events, e.g. someone using the mirror of pride or a wizard using.. well their mirror of pride. The notion of teleportation malfunctioning in that memy way is very LRP, almost as bad as neon green colored clown transformation Wizards possess on some servers. Teleporters can already malfunction and teleport you to wrong destinations despite being callibrated which is much more severe of a punishment/drawback for overusing a teleporter and most importantly doesnt nearly break "immursion" and RP, let alone the fact that teleportation would not work that way, its not some childs card game card that lets you fuse two creatures.
Setting the probability of the event to fire to 0. 0 times something equals zero. Therefor the event …
> Removes Fly Person teleport

- modular_citadel/code/modules/mob/mob.dm
You can now use `!` at the start of your `Say` message to emote everything after it.
`say "!burps loudly"` -> prints the message `burps loudly` like a normal emote
`say ";!screams"` -> prints the message `screams` over the radio, and to those around you.
`say ".s !screams"` -> same as above, but on the security channel.
The custom emote functionality of `*` has been removed.
Fixes #589
Keep it simple, keep it nice.
:cl:
fix: using '!' at the start of Say now emotes everything after it, instead of '*'.
/:cl:
> custom emote in say tweak

- code/datums/traits/_quirk.dm
- code/datums/traits/negative.dm
- code/modules/client/preferences.dm
Acute Blood Deficiency is no longer choosable by any species with the `NOBLOOD` flag or `exotic_blood` variable, in the character creation quirk menu.
Fixes #259
Free quirk points is bad.
:cl:
fix: Species like plasmaman and slimepeople can no longer choose Acute Blood Deficiency for free quirk points.
/:cl:
> quirk blood checking

- code/modules/integrated_electronics/subtypes/output.dm
Makes assemblies speech file under game logging instead of say, because it doesnt fix that format
Makes me not have to code snowflake cases into my parser
server: Assembly speech logs are now under game logs not say logs
/:cl:
> Tweaks assembly logging

- code/modules/reagents/chemistry/holder.dm
Upstream we were testing fractionised reactions, when the testmerge got full merged. As it was found out later this doesn't play well with cooking reactions, so we've got a testmerge to tweak this, but I know you guys have testruns today, and I didn't want you guys to be stuck with broken cooking, so I figured I'd bring this over to you.
I also put this PR in the wrong place before oops.
Allows cooking reactions to not disappear and produce nothing.
:cl: Fermis
fix: returns standard reactions to their normal ratios and fixes cooking reactions.
/:cl:
> Undoes fractioning of reactions.

- code/game/machinery/cryopod.dm
Removes span tags from the cryo alert.
Can't use spans in alerts, dummy, smh.
Fixes #757
Bad spans are bad.
:cl:
fix: Span tags should no longer show up in Head of staff cryo alerts
/:cl:
> Fix head of staff cryo message

- code/modules/mob/living/carbon/human/update_icons.dm
Fixes #758
Humans no longer have digitigrade legs on hardsuits
Humans shouldnt have weird legs
fix: Humans no longer get digitigrade suit overlays
/:cl:
> Fixes digi suits

- code/modules/mob/dead/new_player/new_player.dm
Players were unable to latejoin Omegastation, since the job menu hadn't accounted for some jobs not existing.
This fixes that. 
Runtimes bad.
:cl:
fix: Players are able to latejoin omegastation again
/:cl:
> Hotfix for latejoin Omega jobs

- code/modules/jobs/job_types/atmospheric_technician.dm
- code/modules/jobs/job_types/chief_engineer.dm
- code/modules/jobs/job_types/roboticist.dm
- code/modules/jobs/job_types/station_engineer.dm
This should fix the lack of ID access and pda's for some jobs(Engineer, CE, atmos tech, roboticist).
Fixes: #812
Fixes: #811
PDA's and access for all.
:cl:
fix: Fixed PDA's not spawning for some jobs
fix: Fixed ID Access missing for some jobs
/:cl:
> Fix pda_slot runtime

- code/modules/mob/emote.dm
Fixes an issue where humans were able to use the beep emote.
Fixes #815 
Humans cannot beep.
:cl:
fix: Humans can no longer beep.
/:cl:
> Fixes non-silicons being able to beep

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
Adds a stack of 50 metal and 50 glass to cargo on boxstation and metastation so they don't need to take materials from aux storage at the start of every round.
Adds missing warehouse loot to boxstation.
Cargo shouldn't have to take the materials from aux storage just to use the autolathe.
Warehouse loot was missing from Box
:cl:
add: Added a stack of 50 metal and glass to cargo on Meta and Box.
add: Added loot to warehouse crates on Box.
/:cl:
> Tweaks to Meta and Box cargo

- code/datums/helper_datums/getrev.dm
Fixes #361
Its good to have proper readouts for server revision information
fix: Server revision now reports correctly with the check server revision verb
/:cl:
> Fixes TGS version reporting

- code/modules/tooltip/tooltip.html
This should fix widescreen, *for now*.
A better solution would be to make this whole thing calculate off both width and height, instead of just one of them. However, im happy with this for now.
Fixes: #236
Tooltips should know their place!
:cl:
fix: Tooltips in widescreen mode has been fixed.
/:cl:
> Fixes widescreen for now

- code/modules/mob/living/carbon/damage_procs.dm
- code/modules/mob/living/carbon/human/damage_procs.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/human/species_types/zombies.dm
- code/modules/mob/living/damage_procs.dm
- code/modules/mob/living/silicon/damage_procs.dm
- code/modules/mob/living/silicon/pai/pai_defense.dm
- code/modules/mob/living/simple_animal/damage_procs.dm
- code/modules/spells/spell_types/shapeshift.dm
Manually ports https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9579
:cl: 4dplanner, MMiracles
tweak: Wizard shapeshift now converts damage taken while transformed
fix: transform spell transfers damage correctly instead of healing most of the time
fix: 0% simplemob health maps to 0 carbon health, 100% simplemob to 100% carbon
fix: transforming to a form with brute resistance no longer heals you
fix: transforming back to a species with brute resistance no longer heals you
/:cl:
> Manual port of upstream wizard fix pr

- code/modules/mob/living/carbon/human/species.dm
Temperature alerts are now based on body temperature and burning. Fixes #956 
Fixed weird issues with temperature alerts
:cl:
fix: Temperature alerts no longer show wrong values.
/:cl:
> Fixes temperature alerts

- modular_kepler/code/modules/client/verbs/ooc.dm
- tgstation.dme
This PR adds in a verb which will hard delete a chat object then force recreate it. Sometimes fancy chat fails to load until I manually do the following long-winded procedure:
Fix Chat > Force Reload > Didnt Work > Didnt Work Again > Switch To Old Chat
Fix Chat > Force Reload > Done
This PR adds a verb which does the required steps in less than a second
I should be able to recreate my chat object without having to spend 20 seconds doing it
add: There is now a verb to force-recreate your chat object
/:cl:
> Adds a verb to force recreate the chat object

- .gitignore
This tweaks our `gitignore` file to not show build from `DMITool`
I shouldnt have to deal with 26 uneeded files in my working tree, which my langservers compiled and I had no interaction in making
:cl:
tweak: The gitignore file now ignores compiled DMITool
/:cl:
> Tweaks our gitignore file

- code/modules/clothing/spacesuits/hardsuit.dm
Fixes #955
The sprites for this didn't actually exist for us, so I just removed the overlay entirely. It doesn't impact the functionality aside from being unable to reskin the stripes now, which to be fair you couldn't even do anyway in its current state
Sprites should work
fix: Cydonian armour has sprites now
/:cl:
> Fixes sprites on cydonian armour

- code/modules/mob/living/carbon/human/human.dm
Fixes the following runtime
```
[2019-11-23 20:17:55.527] runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
- To avoid this safety check, set world.loop_checks=0.
- proc name: clean blood (/mob/living/carbon/human/clean_blood)
-   usr: (src)
-   src: Alec Cooper (/mob/living/carbon/human)
-   src.loc: the floor (130,149,2) (/turf/open/floor/plasteel/freezer)
-   call stack:
- Alec Cooper (/mob/living/carbon/human): clean blood()
- Alec Cooper (/mob/living/carbon/human): clean blood()
- Alec Cooper (/mob/living/carbon/human): clean blood()
- Alec Cooper (/mob/living/carbon/human): clean blood()
[many, many more lines of this]
- Alec Cooper (/mob/living/carbon/human): clean blood()
- CallAsync(Alec Cooper (/mob/living/carbon/human), /atom/proc/clean_blood …
```
> Fixes glove washing infinite proc

- _maps/map_files/BoxStation/BoxStation.dmm
This PR adds a chem dispenser to xenobiology, which is required in this population set due to chemistry almost never being available.
MapDiffBot should generate the images
Allows xenobio people to actually do stuff
:cl:
tweak: Xenobio has a chem dispenser now
/:cl:
> Adds in a chem dispenser to xenobiology
